#!/bin/sh

### BEGIN INIT INFO
# Provides: pinaple
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Pinaple NAP service
# Description: Pinaple Bluetooth network access point service
### END INIT INFO

DAEMON=/usr/local/bin/pinapled
DAEMON_NAME=pinaple
DAEMON_USER=root
PIDFILE=/var/run/$DAEMON_NAME.pid

# Change the following line to reflect the name of your network bridge
DAEMON_ARGS=pan0

. /lib/lsb/init-functions

do_start() {
	log_daemon_msg "Starting system $DAEMON_NAME daemon"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --startas $DAEMON --test > /dev/null || return 1
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --startas $DAEMON -- $DAEMON_ARGS || return 2
}

do_stop() {
	log_daemon_msg "Stopping system $DAEMON_NAME daemon"
	start-stop-daemon --stop  --pidfile $PIDFILE
	log_end_msg $?
}

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		do_start
#		case "$?" in
#			0|1) log_end_msg 0 
#			;;
#			2) log_end_msg 1 
#			;;
#		esac
	;;

	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		do_stop()
	;;

	restart|reload|force-reload)
		do_stop
		do_start
	;;

	status)
		status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
	;;

	*)
		echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|restart|status}"
		exit 1
	;;
esac
exit 0



